services:
  postgres_auth:
    image: postgres:latest
    container_name: postgres_auth_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: auth
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "${AUTH_DB_PORT}:5432"
    volumes:
      - auth_data:/var/lib/postgresql/data
      - ./init_scripts/auth:/docker-entrypoint-initdb.d

  postgres_core:
    image: postgres:latest
    container_name: postgres_core_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: core
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "${CORE_DB_PORT}:5432"
    volumes:
      - core_data:/var/lib/postgresql/data
      - ./init_scripts/core:/docker-entrypoint-initdb.d

  postgres_notification:
    image: postgres:latest
    container_name: postgres_notification_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: notification
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "${NOTIFICATION_DB_PORT}:5432"
    volumes:
      - notification_data:/var/lib/postgresql/data
      - ./init_scripts/notification:/docker-entrypoint-initdb.d

  redis:
    image: redis:alpine
    container_name: redis_container
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_UI_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ${PGADMIN_CONTAINER_NAME}
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgres_auth
      - postgres_core
      - postgres_notification
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json:ro

volumes:
  auth_data:
  core_data:
  notification_data:
  redis_data:
  rabbitmq_data:
  pgadmin_data:
